FROM rocm/dev-ubuntu-20.04:4.3-complete

RUN apt update -y
RUN apt install -y  wget \
                    python3-pip
RUN apt install -y hipblas hipsparse rocsparse rocrand rocthrust rocsolver rocfft hipcub rocprim rccl
RUN wget https://github.com/xuhuisheng/rocm-gfx803/releases/download/rocm43/rocblas_2.39.0-8328dcce.dirty_amd64.deb &&\
    dpkg -i rocblas_2.39.0-8328dcce.dirty_amd64.deb &&\
    rm rocblas_2.39.0-8328dcce.dirty_amd64.deb
RUN pip3 install protobuf==3.19.0
RUN wget https://github.com/xuhuisheng/rocm-gfx803/releases/download/rocm43/tensorflow-2.6.0-cp38-cp38-linux_x86_64.whl
RUN python3 -m pip install tensorflow-2.6.0-cp38-cp38-linux_x86_64.whl
RUN rm tensorflow-2.6.0-cp38-cp38-linux_x86_64.whl